### ISSUE TITLE
well go get

### ISSUE THREAD

**Issue by cyberience** [tarancss/ethcli#1]
when go get, I get the following error.

go get -t github.com/tarancss/ethcli

go/pkg/mod/github.com/tarancss/ethcli@v1.1.0/ethcli.go:81:38: undefined: params.TestnetChainConfig

undefined: params.TestnetChainConfig

**Comment by tarancss** [comment]
that variable is defined here: https://github.com/ethereum/go-ethereum/blob/6a62fe399b68ab9e3625ef5e7900394f389adc3a/params/config.go#L95. 

Please ensure you have downloaded the dependencies required in `go.mod`.
